mysteriumnetwork/mysterium-vpn

.travis.yml, README.md, package.json
This allows to run `yarn ci` locally to run all checks easily :)
=> Extract all CI checks into command

src/libraries/api/tequilapi.js, src/renderer/config.js, src/renderer/store/modules/connection.js
=> bugfix: remove connection timeout

src/app/communication/utils.js, src/app/mysterion.js, src/app/window.js, test/unit/app/communication/utils.spec.js
=> fix data passing via onFirstEvent from messageBus

test/.eslintrc, test/unit/app/data-fetchers/proposal-fetcher.spec.js, test/unit/app/statistics/null-collector.spec.js, test/unit/libraries/api/tequilapi.spec.js, test/unit/libraries/functionLooper.spec.js, test/unit/libraries/limited-lnked-list.spec.js, test/unit/main/dependencies/index.spec.js, test/unit/renderer/components/CountrySelect.spec.js, test/unit/renderer/pages/VpnLoader.spec.js
=> fix linter in tests

src/app/di/jpex-container.js, src/app/di/vue-container.js
sorry, lost some changes on master merge to this branch. now this is fixed
=> di-factory instance caching is now switched on by default

src/app/mysterion.js
This bootstrap method is very important, because application won't start if it works incorrectly, but it's very hard to understand what it does - I'm trying to improving readability of it.
=> Refactor Mysterion bootstrap method

src/app/logger.js, src/app/mysterion.js, src/libraries/mysterium-client/launch-daemon/process.js, src/main/index.dev.js, src/renderer/App.vue, src/renderer/pages/VpnLoader.vue, src/renderer/store/modules/connection.js
What do you think about such abstraction?
Few of advantages:
- Future possibility to filter outputted logging levels (easier to find important errors)
- Future possibility to add more levels
- Single place for changing logging format, i.e. including timestamp
- Clear, consistent interface - currently we have a mess around logging
- Future possibility to merge `Logger` and `BugReporting` into one - i.e. Logger.error could send error to sentry.
If you approve this approach, I'll convert other logging usages to this as well :)
=> Add Logger class, use it in Mysterion class

src/app/data-fetchers/proposal-fetcher.js, src/libraries/mysterium-tequilapi/client-factory.js, src/libraries/mysterium-tequilapi/client.js, src/renderer/store/modules/connection.js, src/renderer/store/modules/identity.js, src/renderer/store/modules/main.js, test/unit/app/data-fetchers/proposal-fetcher.spec.js, test/unit/libraries/mysterium-tequilapi/client.spec.js, test/unit/renderer/pages/VpnLoader.spec.js, test/unit/renderer/store/modules/connection.spec.js, test/unit/renderer/store/modules/empty-tequilapi-client-mock.js, test/unit/renderer/store/modules/tequilapi-manipulator.js
Added `TequilapiClient` interface with `HttpTequilapiClient` real implementation and other mock implementations.
=> Fix Flow warnings about TequilapiClient mocks

.eslintrc.js, src/renderer/App.vue
=> hotfix: Lint no restricted globals [error, event]

.eslintrc.js, package.json, src/renderer/App.vue, src/renderer/components/ConnectionButton.vue, src/renderer/components/CountrySelect.vue, src/renderer/components/DisconnectNotificationSetting.vue, src/renderer/components/StatsDisplay.vue, src/renderer/pages/About.vue, src/renderer/pages/Terms.vue, src/renderer/pages/Vpn.vue, src/renderer/pages/VpnLoader.vue, src/renderer/partials/AppError.vue, src/renderer/partials/AppModal.vue, src/renderer/partials/AppNav.vue, src/renderer/partials/AppVisual.vue, yarn.lock
I've enabled base rules for Vue - we will be able to adapt more rules gradually later on, by changing rules level: https://github.com/vuejs/eslint-plugin-vue#bulb-rules
=> Enable eslint-plugin-vue

.eslintrc.js, src/renderer/App.vue, src/renderer/components/ConnectionButton.vue, src/renderer/components/CountrySelect.vue, src/renderer/components/DisconnectNotificationSetting.vue, src/renderer/components/StatsDisplay.vue, src/renderer/pages/About.vue, src/renderer/pages/AppLoading.vue, src/renderer/pages/Terms.vue, src/renderer/pages/Vpn.vue, src/renderer/pages/VpnLoader.vue, src/renderer/partials/AppError.vue, src/renderer/partials/AppModal.vue, src/renderer/partials/AppNav.vue, src/renderer/partials/AppVisual.vue
Increased by 2 levels:
- Priority A: Essential (Error Prevention)
- Priority B: Strongly Recommended (Improving Readability)
=> Increase rules level for vue lint

src/app/bug-reporting/bug-reporter-main.js, src/app/bug-reporting/bug-reporter-renderer.js, src/app/bug-reporting/interface.js, src/app/mysterion.js, src/renderer/components/CountrySelect.vue, src/renderer/dependencies/modules/bug-reporting.js, src/renderer/pages/VpnLoader.vue, src/renderer/store/modules/connection.js, test/unit/renderer/components/CountrySelect.spec.js, test/unit/renderer/store/modules/connection.spec.js
This implicit *ERROR* level causes confusion, lets solve this.
=> Rename error capturing methods on BugReporter

src/renderer/assets/less/5_partials/modal.less, src/renderer/partials/AppError.vue
=> feature/MYS-94 fix z-position of overlay, add feedback button on overlay

CONTRIBUTING.md, README.md
Reviewing this PR commit-by-commit might be easier :)
=> Extract CONTRIBUTING.md, add existing conventions

src/renderer/config.js, src/renderer/pages/VpnLoader.vue
retry 40 times instead of 3 times, loading would take up to 2min
=> bugfix/MYS-43 - increase initialization retry count

.travis.yml
https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A
=> Fix release-candidate deploy rules to fix CI

.eslintignore, CONTRIBUTING.md, src/renderer/dependencies/index.js, src/renderer/main.js, test/unit/karma.conf.js
`> TEST_COVERAGE=true yarn unit`
```
=============================== Coverage summary ===============================
Statements   : 53.89% ( 928/1722 )
Branches     : 57.75% ( 231/400 )
Functions    : 45.81% ( 268/585 )
Lines        : 54.03% ( 918/1699 )
================================================================================
```
=> Test coverage

src/app/mysterion.js, src/app/statistics/startup-event-tracker.js, src/dependencies/statistics.js, src/main/dependencies/modules/application.js, src/renderer/pages/vpn.vue, test/unit/app/statistics/startup-event-tracker.spec.js, test/unit/renderer/pages/vpn.spec.js
=> feature/MYS-69 send app_start & app_start_success

src/app/communication/ipc/main-buffered-ipc.js, src/app/mysterium-vpn.js, src/main/dependencies/modules/application.js, test/unit/app/communication/buffered-ipc.spec.js
=> refactor/MYS-159 move communication in DI

.electron-vue/webpack.renderer.config.js, package.json
=> hotfix/downgrade karma-webpack

package.json
=> set package version to 0.4.0

src/renderer/assets/less/1_generic/text.less, src/renderer/assets/less/index.less, src/renderer/pages/vpn.vue, src/renderer/store/modules/connection.js, test/unit/renderer/store/modules/connection.spec.js
=> IP hidden by default

.gitignore, build/installer.nsh, package.json
Some docs: https://www.electron.build/configuration/nsis
=> Uninstall mysterium_client service in windows installer/uninstaller

package.json, yarn.lock
Already tested on Windows, and it works! 🎉
=> Update mysterium-client-bin to 0.3.2

src/app/communication/message-receiver.js, src/app/events.js, src/app/mysterium-client/process-manager.js, src/app/mysterium-vpn.js, src/libraries/mysterium-client/launch-daemon/launch-daemon-process.js, src/libraries/mysterium-client/monitoring/monitoring.js, src/libraries/subscriber.js, src/main/dependencies/modules/mysterium-client.js, src/renderer/config.js, test/unit/app/communication/utils.spec.js, test/unit/libraries/mysterium-client/launch-daemon/launch-daemon-process.spec.js, test/unit/libraries/subscriber.spec.js
Same as https://github.com/mysteriumnetwork/mysterium-vpn/pull/372, just to `master` to keep `master` in sync
=> [MVPN-239] OS X mysterium client upgrade

package.json, src/libraries/mysterium-client/launch-daemon/launch-daemon-installer.js, src/main/dependencies/modules/mysterium-client.js, test/unit/libraries/mysterium-client/launch-daemon/launch-daemon-installer.spec.js
stuff needed to run 0.4.0 on osx.
could somebody direct me on getting this friendly with Win?
=> feature/MYST-259- myst binary (0.4.0) used in daemon

src/renderer/app.vue, src/renderer/assets/less/4_components/countries.less, src/renderer/pages/vpn.vue, test/unit/renderer/pages/vpn.spec.js
FInished Vaidotas PR: https://github.com/mysteriumnetwork/mysterium-vpn/pull/366
=> [MVPN-334] Move identity registration to vpn page

features.prod.json
This shows identity icon, but doesn't force users to register yet.
=> Enable payments

.flowconfig, package.json, src/app/bug-reporting/tequilapi-client-with-metrics.js, src/app/communication-bindings.js, src/app/connection/tequilapi-connection-establisher.js, src/app/countries/parsing.js, src/app/data-fetchers/country-list.js, src/app/data-fetchers/proposal-fetcher.js, src/app/data-fetchers/tequilapi-proposal-fetcher.js, src/app/identity-manager.js, src/app/messages.js, src/renderer/store/modules/identity.js, test/unit/app/countries/reporting.spec.js, test/unit/app/data-fetchers/country-list.spec.js, test/unit/app/data-fetchers/tequilapi-proposal-fetcher.spec.js, test/unit/renderer/components/identity-registration.spec.js, test/unit/renderer/pages/vpn.spec.js, test/unit/renderer/store/modules/empty-tequilapi-client-mock.js, test/unit/renderer/store/modules/identity.spec.js, yarn.lock
Currently blocked by: https://github.com/mysteriumnetwork/js-tequilapi/pull/31
=> [Feature-400] Tequilapi package upgrade

src/app/bug-reporting/bug-reporter-renderer.js, src/app/connection/tequilapi-connection-establisher.js, src/app/countries/utils.js, src/libraries/mysterium-client/service-manager/service-manager-process.js, src/renderer/store/modules/connection.js, test/unit/app/countries/utils.spec.js
Lets add these two fixes to `release/0.7` branch for new release (just cherry-picked them):
https://github.com/mysteriumnetwork/mysterium-vpn/pull/432
https://github.com/mysteriumnetwork/mysterium-vpn/pull/433
=> Add bugfixes to release

.travis.yml
=> Add stages to CI

.travis.yml
Currently, deploy is done on each job in "Testing" phase - this fixed it by adding separate stage, which is run on a single machine:
=> Fix .travis.yml - deploy only in a single job

src/renderer/components/country-select.vue, test/unit/renderer/components/country-select.spec.js
=> Unify proposal labels in list and on selected item

src/renderer/components/identity-menu.vue, test/unit/renderer/components/identity-menu.spec.js
https://github.com/mysteriumnetwork/mysterium-vpn/issues/458
=> [MVPN-458] Allow changing eth address

src/main/tray/menu-builder.js, test/unit/main/tray/menu-builder.spec.js
=> Group VPN/Provider items separately in tray

src/libraries/mysterium-client/launch-daemon/launch-daemon-installer.js, src/libraries/mysterium-client/service-manager/service-manager-installer.js, test/unit/libraries/mysterium-client/launch-daemon/launch-daemon-installer.spec.js, test/unit/libraries/mysterium-client/service-manager/service-manager-installer.spec.js
Fixes #495 
SO that people can configure NAT port forwarding for a known port number
if uPNP doesn't work for them
=> Use static 1194 openvpn port

yarn.lock
Closes #510, closes #511, closes #512 and closes #513.
=> Apply dependabot security fixes
